### PR TITLE
Final updates to `SentienceModule`

### PR DESCRIPTION
**Pull request by KazutoKashima**
What's new?:
- Scarlet's Sentience module has been updated to now update the values of her Moods until they are no longer 0 (if possible)
- calls on the database for the average sentience score to assign a mood in accordance to the score
- She will assign a room at random to every mood update, essentially "exploring" her scenary

### CODE REVIEW

**Review by joseywoermann — CHANGES_REQUESTED** [review]

**Comment by KazutoKashima** [comment]
@joseywoermann the `HEAD` stuff was removed in commit `209d6ff`

**Comment by joseywoermann** [comment]
> @joseywoermann the `HEAD` stuff was removed in commit `209d6ff`

Weird, I can still see it in the code & diff?
https://github.com/ScarletAI/Scarlet/blob/SentienceReview/database/models/mood.data.json

**Comment by KazutoKashima** [comment]
I'll try pushing again, and seeing if it fixes it

**Review by joseywoermann — APPROVED** [review]
LGTM

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
